
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: eventlogger-sqlserver
    environment:
      MSSQL_DBNAME: "EventLogsDb"
      SA_PASSWORD: "Pass@word1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - eventlogger-network

  mongo:
    image: mongo:4.4
    container_name: eventlogger-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - eventlogger-network
volumes:
  sqlserver_data:
  mongo_data:
  
networks:
  eventlogger-network:
    driver: bridge   